spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        hbm2ddl:
          auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres #root #
  flyway:
    baseline-on-migrate: true

#logging:
#  level:
#    ROOT: DEBUG
