spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        hbm2ddl:
          auto: create
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    #password: postgres
  flyway:
    baseline-on-migrate: true
    baselineVersion: 0
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
    check-location: true
#logging:
#  level:
#    ROOT: DEBUG
